cricket_scorer/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login_view, name="login"),
    path('signup/', views.signup_view),
    path('user/', include('user.urls')),
    path('logout/', views.logout_view),
    path('walkthrough/', views.walkthrough),
    path('', views.index, name="index")
]

urlpatterns += staticfiles_urlpatterns()

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.index, name="dashboard"),
    path('player_pool/', views.player_pool, name="player_pool"),
    path('add_player/', views.add_player, name="add_player"),
    path('track_match/<int:match_id>/', views.tracker, name="track_match"),
    path('match_details/', views.match_details, name="match_details"),
    path('tracked_matches/', views.tracked_matches, name="tracked_matches"),
    path('update_score/', views.update_score, name="update_score"),
    path('player_profile/<int:player_id>/', views.player_profile, name="player_profile"),
    path('end_match/<int:match_id>/', views.end_match, name="end_match"),
    path('match_stats/<int:match_id>/', views.match_stats, name="match_stats"),
    path('undo/<int:match_id>/', views.undo, name="undo"),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Player(models.Model):
    roles = [
        ('Batsman', 'Batsman'),
        ('Bowler', 'Bowler'),
        ('All Rounder', 'All Rounder')
    ]
    styles = [
        ('RHB', 'RHB - Right Handed'),
        ('LHB', 'LHB - Left Handed')
    ]
    name = models.CharField(max_length=50)
    role = models.CharField(max_length=20, choices=roles, default='All Rounder')
    bat_style = models.CharField(max_length=20, choices=styles, default='RHB')
    bowl_style = models.CharField(max_length=20, choices=styles, default='RHB')
    matches = models.IntegerField(default=0)
    runs = models.IntegerField(default=0)
    strike_rate = models.FloatField(default=0.0)
    overs = models.FloatField(default=0.0)
    wickets = models.IntegerField(default=0)
    economy = models.FloatField(default=0.0)
    pool_admin = models.ForeignKey(User, on_delete=models.CASCADE, default=None)


class Match(models.Model):
    team_select = [
        ('team1', 'Team 1'),
        ('team2', 'Team 2')
    ]
    overs_per_team = models.IntegerField(
        validators=[
            MinValueValidator(1),
            MaxValueValidator(50)
        ]
    )
    players_per_team = models.IntegerField(
        validators=[
            MinValueValidator(2),
            MaxValueValidator(15)
        ]
    )
    toss_won_by = models.CharField(choices=team_select, default='team1', max_length=10)
    batting_first = models.CharField(choices=team_select, default='team1', max_length=10)
    team1_score = models.IntegerField(default=0)
    team2_score = models.IntegerField(default=0)
    result = models.CharField(max_length=30)
    pool_admin = models.ForeignKey(User, default=None, on_delete=models.CASCADE)


class ByBallStat(models.Model):
    ball_id = models.AutoField(primary_key=True)
    match_id = models.ForeignKey(Match, default=0, on_delete=models.CASCADE)
    inning = models.IntegerField()
    over = models.IntegerField()
    ball = models.IntegerField()
    strike = models.CharField(max_length=50, )
    non_strike = models.CharField(max_length=50, )
    bowler = models.CharField(max_length=50, )
    is_wide = models.BooleanField(default=False)
    is_no_ball = models.BooleanField(default=False)
    batsman_runs = models.IntegerField(choices=[(i, i) for i in range(9)])
    total_runs = models.IntegerField()
    player_dismissed = models.CharField(max_length=50, default=None)
    dismissal_kind = models.CharField(max_length=50, default=None, choices=[
        ('Bowled', 'Bowled'),
        ('Caught', 'Caught'),
        ('Runout', 'Runout'),
        ('Stumped', 'Stumped')
    ])
    fielder = models.CharField(max_length=50, default=None)

user/forms.py
from django import forms
from . import models


class AddPlayerForm(forms.ModelForm):
    class Meta:
        model = models.Player
        fields = ['name', 'role', 'bat_style', 'bowl_style']


class MatchForm(forms.ModelForm):
    class Meta:
        model = models.Match
        fields = ['overs_per_team', 'players_per_team', 'toss_won_by', 'batting_first']

user/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseServerError
from . import forms,models
from .models import Match
import json
from django.db.models import Sum, Count

# Create your views here.
@login_required(login_url='/login/')
def index(request):
    no_of_players = models.Player.objects.all().filter(pool_admin=request.user).count()
    no_of_matches = models.Match.objects.all().filter(pool_admin=request.user).count()
    return render(request, "user/dashboard.html", {'no_of_players': no_of_players, 'no_of_matches': no_of_matches})

@login_required(login_url='/login/')
def player_pool(request):
    form = forms.AddPlayerForm()
    players = models.Player.objects.all().filter(pool_admin=request.user).order_by('name')
    match_ids = models.Match.objects.filter(pool_admin=request.user).values_list('id', flat=True)
    names = [i['name'] for i in players.values('name')]
    player_profiles = {player.name: {'id': player.id, 'name': player.name, 'role': player.role, 'innings': 0, 'bat_style': player.bat_style, 'bowl_style': player.bowl_style, 'runs': 0, 'balls_faced': 0, 'wickets': 0, 'balls_bowled': 0} for player in players}

    for row in models.ByBallStat.objects.filter(match_id__in=match_ids).values('strike').annotate(Sum('batsman_runs'), Count('ball_id')):
        player_profiles[row['strike']]['runs'] = row['batsman_runs__sum']
        player_profiles[row['strike']]['balls_faced'] = row['ball_id__count']

    for row in models.ByBallStat.objects.filter(match_id__in=match_ids).values('strike').annotate(Count('match_id', distinct=True)):
        player_profiles[row['strike']]['innings'] = row['match_id__count']
    
    for row in models.ByBallStat.objects.exclude(player_dismissed="").filter(match_id__in=match_ids).values('bowler').annotate(Count('player_dismissed')):
        player_profiles[row['bowler']]['wickets'] = row['player_dismissed__count']

    for row in models.ByBallStat.objects.exclude(is_wide=True, is_no_ball=True).filter(match_id__in=match_ids).values('bowler').annotate(Count('ball_id')):
        player_profiles[row['bowler']]['balls_bowled'] = row['ball_id__count']

    for row in models.ByBallStat.objects.filter(match_id__in=match_ids).values('bowler').annotate(Sum('total_runs')):
        player_profiles[row['bowler']]['runs_conceded'] = row['total_runs__sum']

    player_profiles = [player_profiles[name] for name in player_profiles]

    highest_run_scorer = sorted(player_profiles, key=lambda x: x['runs'], reverse=True)[0] if players.count() > 0 else 'NA'
    highest_wicket_taker = sorted(player_profiles, key=lambda x: x['wickets'], reverse=True)[0] if players.count() > 0 else 'NA'

    for d in player_profiles:
        d['strike_rate'] = round(d['runs'] * 100 / d['balls_faced'], 2) if d['balls_faced'] > 0 else 0.0
        d['economy'] = round(d['runs_conceded'] / (d['balls_bowled'] / 6), 2) if d['balls_bowled'] > 0 else 0.0

    best_strike_rate = sorted(player_profiles, key=lambda x: x['strike_rate'], reverse=True)[0] if players.count() > 0 else 'NA'
    best_economy = sorted(player_profiles, key=lambda x: x['economy'] if x['economy'] > 0 else 36)[0] if players.count() > 0 else 'NA'
    
    return render(request, 'user/player_pool.html', 
    {
        "player_count": players.count(), 
        'profiles': player_profiles, 
        "form": form, 
        "highest_run_scorer": highest_run_scorer,
        "highest_wicket_taker": highest_wicket_taker,
        "best_strike_rate": best_strike_rate,
        "best_economy": best_economy
    })


@login_required(login_url='/login/')
def tracked_matches(request):
    matches = models.Match.objects.all().filter(pool_admin=request.user)
    return render(request, 'user/matches_tracked.html', {'matches_tracked': matches})


@login_required(login_url='/login/')
def add_player(request):
    if request.method == 'POST':
        form = forms.AddPlayerForm(request.POST)
        if form.is_valid():
            player = form.save(commit=False)
            player.pool_admin = request.user
            player.save()
            return redirect('user:player_pool')
        else:
            form = forms.AddPlayerForm()
    return redirect('user:player_pool')


@login_required(login_url='/login/')
def match_details(request):
    if request.method == 'POST':
        form = forms.MatchForm(request.POST)
        if form.is_valid():
            match = form.save(commit=False)
            match.pool_admin = request.user
            match.result = 'In Progress'
            match.save()
            return redirect('user:track_match', match_id=match.id)
        else:
            return render(request, 'user/add_match_details.html', {'match_form': form})
    else:
        form = forms.MatchForm()
        return render(request, 'user/add_match_details.html', {'match_form': form})


@login_required(login_url='/login/')
def tracker(request, match_id):
    player_pool = models.Player.objects.all().filter(pool_admin=request.user).order_by('name')
    balls = models.ByBallStat.objects.all().filter(match_id=match_id)
    status = 'new' if balls.count() == 0 else 'old'
    resp_data = dict()
    resp_data['team1_over'] = 0
    resp_data['team1_ball'] = 0
    resp_data['team2_over'] = 0
    resp_data['team2_ball'] = 0
    if status == 'old':
        resp_data['strike'] = balls.last().strike
        resp_data['non_strike'] = balls.last().non_strike
        resp_data['bowler'] = balls.last().bowler
        resp_data['inning'] = balls.last().inning
        resp_data['team1_over'] = balls.filter(inning=1).last().over
        resp_data['team1_ball'] = balls.filter(inning=1).last().ball
        if resp_data['inning'] == 2:
            resp_data['team2_over'] = balls.filter(inning=2).last().over
            resp_data['team2_ball'] = balls.filter(inning=2).last().ball
        resp_data['team1_score'] = balls.filter(inning=1).aggregate(Sum('total_runs'))['total_runs__sum']
        resp_data['team2_score'] = balls.filter(inning=2).aggregate(Sum('total_runs'))['total_runs__sum']
        resp_data['team1_wickets'] = balls.filter(inning=1).exclude(player_dismissed="").count()
        resp_data['team2_wickets'] = balls.filter(inning=2).exclude(player_dismissed="").count()
        for key in ['team1_score', 'team2_score', 'team2_wickets', 'team1_wickets']:
            resp_data[key] = 0 if resp_data[key] is None else resp_data[key]
    resp_data['match_length'] = models.Match.objects.filter(id=match_id).first().overs_per_team
    resp_data['match_players'] = models.Match.objects.filter(id=match_id).first().players_per_team
    resp_data['player_pool'] = player_pool
    resp_data['match_id'] = match_id
    resp_data['status'] = status
    # print(resp_data)
    # return HttpResponse(resp_data)
    return render(request, 'user/track_match.html/', resp_data)


@login_required(login_url='/login/')
def update_score(request):
    form = request.POST
    ball = models.ByBallStat()
    ball.match_id = models.Match.objects.all().filter(id=form.get('match_id'))[0]
    ball.inning = form.get('inning')
    ball.over = form.get('over')
    ball.ball = form.get('ball')
    ball.strike = form.get('strike')
    ball.non_strike = form.get('non_strike')
    ball.bowler = form.get('bowler')
    ball.is_wide = form.get('is_wide') == 'true'
    ball.is_no_ball = form.get('is_no_ball') == 'true'
    ball.batsman_runs = form.get('batsman_runs')
    ball.total_runs = form.get('total_runs')
    ball.player_dismissed = form.get('player_dismissed')
    ball.dismissal_kind = form.get('dismissal_kind')
    ball.fielder = form.get('fielder')
    ball.save()
    return HttpResponse("success")

@login_required(login_url="/login/")
def player_profile(request, player_id):
    player_name = models.Player.objects.filter(pool_admin=request.user, id=player_id).values_list('name', flat=True)[0]
    matches = models.Match.objects.filter(pool_admin=request.user).values_list('id', flat=True)
    all_balls_faced = models.ByBallStat.objects.filter(strike=player_name).all()
    performances = {}
    runs_scored_per_match = list(map(lambda x: str(x['batsman_runs__sum']), all_balls_faced.values('match_id').annotate(Sum('batsman_runs'))))
    for match in all_balls_faced.exclude(is_wide=True).values('match_id').annotate(Count('ball_id'), Sum('batsman_runs')):
        performances[match['match_id']] = {}
        performances[match['match_id']]['match_id'] = match['match_id']
        performances[match['match_id']]['runs'] = match['batsman_runs__sum']
        performances[match['match_id']]['balls_faced'] = match['ball_id__count']
        performances[match['match_id']]['fours'] = 0
        performances[match['match_id']]['sixes'] = 0
        performances[match['match_id']]['strike_rate'] = round(performances[match['match_id']]['runs'] * 100 / performances[match['match_id']]['balls_faced'], 2) if performances[match['match_id']]['balls_faced'] > 0 else 0.0
    
    for match in all_balls_faced.exclude(is_wide=True).filter(batsman_runs=4).values('match_id').annotate(Count('ball_id')):
        performances[match['match_id']]['fours'] = match['ball_id__count']

    for match in all_balls_faced.exclude(is_wide=True).filter(batsman_runs=6).values('match_id').annotate(Count('ball_id')):
        performances[match['match_id']]['sixes'] = match['ball_id__count']
    
    performances = list(performances.values())

    run_distribution = []
    for i in range(7):
        run_distribution.append(str(all_balls_faced.filter(batsman_runs=i).count()))
    run_distribution = ', '.join(run_distribution)

    total_runs = sum(all_balls_faced.values_list('batsman_runs', flat=True))
    out_times = models.ByBallStat.objects.filter(player_dismissed=player_name).values_list('ball_id', flat=True).count()
    average = round(total_runs / out_times, 2) if out_times > 0 else 'na'

user/templates/user/add_match_details.html
{% extends 'base_template.html' %}

{% block content %}

{% load static %}

    <div class="container mt-5">
        <div class="row">
    
            <div class="col-sm-5">
                <div class="card">
                    <div class="card-header bg-dark text-center">
                        <h4 class="text-success font-weight-bold mt-1">Add Match Details</h4>
                    </div>
        
                    <form action="" method="post" id="match-form">
                        {% csrf_token %}
                        <div class="card-body">
                            {{match_form}}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-outline-success">Start Match</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="col-sm-7 text-center">
                <img src="{% static 'images/add_match_details_illus.svg' %}" style="width: 70%; margin-top: 5vw;" alt="">
            </div>
        </div>
    </div>

    <script>
        $(document).ready(() => {
            $('#matchModal').modal('show');
            $('input[type="text"]').addClass('form-control mb-3');
            $('input[type="number"]').addClass('form-control mb-3');
            $('input[type="checkbox"]').addClass('form-check-input mb-3 mx-3');
            $('select').addClass('form-control mb-3');
        });
    </script>

    <!-- {% load static %} -->
    <!-- <script src="{% static 'scripts/add_match_details.js' %}"></script> -->

{% endblock %}

user/templates/user/dashboard.html
{% extends 'base_template.html' %}

{% block content %}
    <div class="row mt-3 ml-3 mb-0">
        <h3 class="text-success">Hey There {{request.user}}!</h3>
    </div>
    <hr class="mx-3 mt-0">
    <div class="row mx-1 mt-4">

        <div class="col-sm-8">
            <div class="card border rounded mt-2 mb-5 shadow-card">
                <div class="card-header text-success">
                    <div class="row">
                        <div class="col-xl-9 col-lg-6 col-md-6">
                            <h4 class="mt-1">Player Pool</h4>
                        </div>
                        <div class="col-xl-3 col-lg-6 col-md-6 text-right">
                            <a href="/user/player_pool" class="btn btn-outline-success">View Players</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <h5>
                        Total no of players: {{no_of_players}}
                    </h5>
                </div>
            </div>

            <div class="card border rounded my-5 shadow-card">
                <div class="card-header text-success">
                    <div class="row">
                        <div class="col-xl-9 col-lg-6 col-md-6">
                            <h4 class="mt-1"> Track Match </h4>
                        </div>
                        <div class="col-xl-3 col-lg-6 col-md-6 text-right">
                            <a href="{% url 'user:tracked_matches' %}" class="btn btn-outline-success">View Matches</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <h5>
                        Total no of matches played: {{no_of_matches}}
                    </h5>
                </div>
            </div>

            <div class="text-center my-5">
                <a href="{% url 'user:match_details' %}" class="btn btn-large btn-outline-success"> <span class="fas fa-plus"></span> Track New Match</a>
            </div>
        </div>

        <div class="col-sm-4">
            {% load static %}
            <img src="{% static 'images/dashboard_illus.svg' %}" alt="" style="width: 95%;">
        </div>
    </div>
{% endblock %}

user/templates/user/track_match.html
{% extends 'base_template.html' %} 

{% block content %} 

{% load static %}

    {% if status in 'old' %}
        <script>
            var is_old = true;
        </script>
    {% else %}
        <script>
            var is_old = false;
        </script>
    {% endif %}

    <div class="container my-3" id="scorer_container">
        <div class="row bg-dark text-success" id="score-section">
            <div class="col-6 text-center my-2">
                <h6 class="font-weight-bold my-2">Team X</h6>

                {% if status in 'new' %}
                    <h1 class="display-4" id="tscore_1">0/0</h1>
                    <h6 class="font-weight-bold my-2">Overs: <span id="overs_1">0.0</span></h6>
                {% else %}
                    <h1 class="display-4" id="tscore_1">{{team1_score}}/{{team1_wickets}}</h1>
                    <h6 class="font-weight-bold my-2">Overs: <span id="overs_1">{{team1_over}}.{{team1_ball}}</span></h6>
                {% endif %}
                

                <input type="hidden" name="match_length" value="{{match_length}}">
                <input type="hidden" name="players_per_team" value="{{match_players}}">
                {% if status in 'old' %}
                    <input type="hidden" name="batsman_at_0" value="{{strike}}">
                    <input type="hidden" name="batsman_at_1" value="{{non_strike}}">
                    <input type="hidden" name="bowler_now" value="{{bowler}}">
                    <input type="hidden" name="overs_done1" value="{{team1_over}}">
                    <input type="hidden" name="balls_done1" value="{{team1_ball}}">
                    <input type="hidden" name="overs_done2" value="{{team2_over}}">
                    <input type="hidden" name="balls_done2" value="{{team2_ball}}">
                    <input type="hidden" name="inning" value="{{inning}}">
                    <input type="hidden" name="team1_score" value={{team1_score}}>
                    <input type="hidden" name="team2_score" value={{team2_score}}>
                    <input type="hidden" name="team1_wickets" value={{team1_wickets}}>
                    <input type="hidden" name="team2_wickets" value={{team2_wickets}}>
                {% endif %}

            </div>
            <div class="col-6 text-center my-2">
                <h6 class="font-weight-bold my-2">Team X</h6>
                
                {% if status in 'new' %}
                    <h1 class="display-4" id="tscore_2">0/0</h1>
                    <h6 class="font-weight-bold my-2">Overs: <span id="overs_2">0.0</span></h6>
                {% else %}
                    <h1 class="display-4" id="tscore_2">{{team2_score}}/{{team2_wickets}}</h1>
                    <h6 class="font-weight-bold my-2">Overs: <span id="overs_2">{{team2_over}}.{{team2_ball}}</span></h6>
                {% endif %}
                
            </div>
            <div class="col-12">
                <div class="row mb-4">
                    <div class="col-5">
                        <p class="text-center my-2">Strike : <span id="strike_batsman">{{strike}}</span>* <button class="btn btn-sm btn-outline-warning p-0 px-1" id="change_batsman_btn">Change</button></p>        
                    </div>
                    <div class="col-7">
                        <p class="text-center my-2">Bowler : <span id="current_bowler">{{bowler}}</span> <button class="btn btn-sm btn-outline-warning p-0 px-1" id="change_bowler_btn">Change</button></p>
                    </div>
                </div>
                <h6 class="text-center my-2" id="equation"> First Innings in Progress </h6>
                <div class="text-center my-3">
                    <a href="{% url 'user:match_stats' match_id %}" class="btn btn-outline-success btn-sm">Match Stats</a>
                </div>
            </div>
            <div class="col-12 my-3" id="remote_container">
                <div class="card bg-dark">
                    <div class="card-header">
                        <h6 class="font-weight-bold text-center">Remote</h6>
                    </div>
                    <form action="" method="post" class="text-success" id="scorer_form">
                        <div class="card-body">
                            <div class="form-group">
                                {% csrf_token %}
                                <input type="hidden" name="match_id" value="{{match_id}}">
                                <label for="batsman_runs">Runs Scored</label>
                                <select name="batsman_runs" id="batsman_runs">
                                        {% for i in '012345678' %}
                                            <option value="{{i}}">{{i}}</option>
                                        {% endfor %}
                                    </select>
                            </div>
                            <div class="row mt-3">
                                <div class="form-group col">
                                    <label for="is_wide">Wide</label>
                                    <input type="checkbox" name="is_wide" id="is_wide">
                                </div>
                                <div class="form-group col">
                                    <label for="is_no_ball">No Ball</label>
                                    <input type="checkbox" name="is_no_ball" id="is_no_ball">
                                </div>
                                <div class="form-group col">
                                    <label for="is_wicket">Wicket</label>
                                    <input type="checkbox" name="is_wicket" id="is_wicket">
                                </div>
                            </div>
                            <div class="form-group d-none wicket_event">
                                <label for="dismissal_kind">Dismissal Kind</label>
                                <select name="dismissal_kind" id="dismissal_kind">
                                        <option value="Bowled" selected>Bowled</option>
                                        <option value="Caught">Caught</option>
                                        <option value="Runout">Runout</option>
                                        <option value="Stumped">Stumped</option>
                                    </select>
                            </div>
                            <div class="form-group d-none wicket_event">
                                <label for="player_dismissed">Batsman Dismissed</label>
                                <select name="player_dismissed" id="player_dismissed">
                                        <!-- <option value=0>Strike Batsman</option>
                                        <option value=1>Non Striker</option> -->
                                </select>
                            </div>
                            <div class="form-group d-none fielder_involved">
                                <label for="fielder">Fielder or Wicket-Keeper</label>
                                <select name="fielder" id="fielder">
                                        {% for player in player_pool %}
                                            <option value="{{player.name}}">{{player.name}}</option>
                                        {% endfor %}
                                    </select>
                            </div>
                        </div>
                        <div class="card-footer text-center">
                            <div class="row">
                                <div class="col">
                                    <button type="submit" class="btn btn-outline-success btn-sm">Update</button>
                                </div>
                                </form>
                                <div class="col">
                                    <button id="changeStrikeBtn" class="btn btn-outline-info btn-sm">Change Strike</button>
                                </div>
                                <div class="col">
                                    <a href="{% url 'user:undo' match_id %}" class="btn btn-outline-warning btn-sm">Undo</a>
                                </div>
                            </div>
                        </div>
                </div>
            </div>
            <div class="col-12 my-3 text-center">
                <div class="col-6 mx-auto">
                    <a href="{% url 'user:end_match' match_id %}" class="btn btn-outline-danger btn-sm">End Match</a>
                </div>
            </div>
        </div>
    </div>

    <div class="modal" id="batsmen-modal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header bg-dark text-success">
                    <h4 class="font-weight-bold">Select Batsmen</h4>
                    <button class="btn" data-dismiss="modal"><span class="fas fa-window-close text-success"></span></button>
                </div>
                <form action="" id="batsmen-form">
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="strike_batsman">Striker</label>
                            <select name="strike_batsman" id="strike_batsman">
                                {% for player in player_pool %}
                                    <option value="{{player.name}}">{{player.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="non_strike_batsman">Non Striker</label>
                            <select name="non_strike_batsman" id="non_strike_batsman">
                                {% for player in player_pool %}
                                    <option value="{{player.name}}">{{player.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer bg-dark">
                        <button type="submit" class="btn btn-outline-success">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal" id="new-batsman-modal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header bg-dark text-success">
                    <h4 class="font-weight-bold">Select New Batsmen</h4>
                    <button class="btn" data-dismiss="modal"><span class="fas fa-window-close text-success"></span></button>
                </div>
                <form action="" id="new-batsman-form">
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="new_batsman">Batsman</label>
                            <select name="new_batsman" id="new_batsman">
                                {% for player in player_pool %}
                                    <option value="{{player.name}}">{{player.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer bg-dark">
                        <button type="submit" class="btn btn-outline-success">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal" id="bowler-modal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header bg-dark text-success">
                    <h4 class="font-weight-bold">Select Bowler</h4>
                    <button class="btn" data-dismiss="modal"><span class="fas fa-window-close text-success"></span></button>
                </div>
                <form action="" id="bowler-form">
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="bowler">Bowler</label>
                            <select name="bowler" id="bowler">
                                {% for player in player_pool %}
                                    <option value="{{player.name}}">{{player.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer bg-dark">
                        <button type="submit" class="btn btn-outline-success">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(() => {
            if(!is_old){
                $('#batsmen-modal').modal('show');
            }
            $('input[type="text"]').addClass('form-control mb-3');
            $('input[type="number"]').addClass('form-control mb-3');
            $('input[type="checkbox"]').addClass('form-check-input mb-3 mx-3');
            $('select').addClass('form-control mb-3');
        });
    </script>
    <script src="{% static 'scripts/update_score.js' %}"></script>
    <script src="{% static 'scripts/scorer.js' %}"></script>
{% endblock %}